In [1]:
import numpy as np

In [2]:
my_arr = np.arange(1000000)

In [3]:
my_list = list(range(1000000))

In [4]:
%time for _ in range(10): my_arr = my_arr * 2 #wall time -> time taken to compute from the start to end

Wall time: 29 ms


In [5]:
%time for _ in range(10): my_list = [x * 2 for x in my_list]

Wall time: 1.86 s


NumPy-based algorithms are generally 10 to 100 times faster (or more) than their pure Python counterparts and use significantly less memory

# 4.1 The NumPy ndarray: A Multidimensional Array Object

In [6]:
data = np.random.randn(2, 3) #ndimensional array of random numbers from normal distribution

In [7]:
data

array([[ 1.39264046,  0.71739099, -0.3372709 ],
       [ 0.94619384,  0.88730622,  0.69813974]])

In [8]:
data * 10

array([[13.92640463,  7.17390992, -3.37270901],
       [ 9.46193842,  8.87306224,  6.98139735]])

In [9]:
data + data

array([[ 2.78528093,  1.43478198, -0.6745418 ],
       [ 1.89238768,  1.77461245,  1.39627947]])

In [10]:
data - data

array([[0., 0., 0.],
       [0., 0., 0.]])

In [11]:
data / data

array([[1., 1., 1.],
       [1., 1., 1.]])

Remember: Without () is an attribute and not a method

In [12]:
data.shape # returns the shape or order of array/matrix

(2, 3)

In [13]:
data.dtype #returns the data type of array (Homogenous) 

dtype('float64')

## Creating ndarrays

In [14]:
data1 = [6, 8, 9, 1, 7.8, 5, 10.25]

In [15]:
arr1 = np.array(data1)

In [16]:
arr1 #Vector of 7x1

array([ 6.  ,  8.  ,  9.  ,  1.  ,  7.8 ,  5.  , 10.25])

In [17]:
arr1.shape

(7,)

In [18]:
arr1.dtype

dtype('float64')

In [19]:
data2 = [[1, 4, 8, 7], [5, 4, 6, 2]]

In [20]:
arr2 = np.array(data2)

In [21]:
arr2 #Matrix of order: 2x4

array([[1, 4, 8, 7],
       [5, 4, 6, 2]])

In [22]:
arr2.shape

(2, 4)

In [23]:
arr1.dtype

dtype('float64')

In [24]:
arr2.dtype

dtype('int32')

In [25]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [26]:
np.zeros((5, 4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [27]:
np.empty((2, 3, 2)) #3d array, .empty() returns the garbage value

array([[[1.20703182e-311, 3.16202013e-322],
        [0.00000000e+000, 0.00000000e+000],
        [0.00000000e+000, 2.46448357e+184]],

       [[1.51169307e+160, 1.95333776e+184],
        [1.83228173e-076, 1.15433120e-071],
        [5.99386424e-038, 1.85331671e-051]]])

In [28]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [29]:
np.arange((10)).reshape(2, 5) #.reshape() -> changes the order wrt given arguments

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [30]:
np.ones(14)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [31]:
np.ones((7, 2))

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [32]:
np.asarray([5, 4, 4, 8, 7]) #Convert input to ndarray, but do not copy if the input is already an ndarray

array([5, 4, 4, 8, 7])

In [33]:
np.ones_like([10, 5, 7, 4]) #produces a ones array of the same shape and dtype

array([1, 1, 1, 1])

In [34]:
np.empty_like(data1) #Create new arrays by allocating new memory, but do not populate with any values like ones and zeros

array([ 6.  ,  8.  ,  9.  ,  1.  ,  7.8 ,  5.  , 10.25])

In [35]:
#Produce an array of the given shape and dtype with all values set to the indicated “fill value”
np.full(shape=(5,2), fill_value=7) 

array([[7, 7],
       [7, 7],
       [7, 7],
       [7, 7],
       [7, 7]])

In [36]:
np.eye(5) #identity matrix (Square matrix)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [37]:
np.eye(1)

array([[1.]])

In [38]:
np.eye(3, dtype=int)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [39]:
np.identity(5) #Same as above

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

## Data Types for ndarrays

In [40]:
arr1 = np.array([1, 2, 3], dtype=float)

In [41]:
arr1

array([1., 2., 3.])

In [42]:
arr2 = np.array([7, 8, 9, 10, 11], dtype=int)

In [43]:
arr2

array([ 7,  8,  9, 10, 11])

In [44]:
arr2.dtype

dtype('int32')

In [45]:
arr1.dtype

dtype('float64')

In [46]:
arr3 = np.array(['a', 'b', 'c'])

In [47]:
arr3

array(['a', 'b', 'c'], dtype='<U1')

In [48]:
arr3.dtype

dtype('<U1')

In [49]:
arr4 = np.array(['stringOne', 'string_two', '$tring 3'])

In [50]:
arr4

array(['stringOne', 'string_two', '$tring 3'], dtype='<U10')

Table 4-2. NumPy data types

In [51]:
arr = np.array([2, 5, 7, 98])

In [52]:
arr

array([ 2,  5,  7, 98])

In [53]:
arr.dtype

dtype('int32')

In [54]:
float_arr = arr.astype(np.float64) # .astype() converts the array to given dtype, casting

In [55]:
float_arr

array([ 2.,  5.,  7., 98.])

In [56]:
arr = np.array([3.7, -1.2, -2.6, 0.5, 12.9, 10.1])

In [57]:
int_arr = arr.astype(int)

In [58]:
int_arr

array([ 3, -1, -2,  0, 12, 10])

In [59]:
arr = np.array(['5.62', '784.21', '0.2002'], dtype=np.string_)

In [60]:
string_arr = arr.astype(np.float64)

In [61]:
string_arr

array([5.6200e+00, 7.8421e+02, 2.0020e-01])

In [62]:
int_arr

array([ 3, -1, -2,  0, 12, 10])

In [63]:
float_arr

array([ 2.,  5.,  7., 98.])

In [64]:
int_arr.astype(float_arr.dtype)

array([ 3., -1., -2.,  0., 12., 10.])

## Arithmetic with NumPy Arrays

In [65]:
arr = np.array([[1, 2, 3], [8, 9, 10]])

In [66]:
arr

array([[ 1,  2,  3],
       [ 8,  9, 10]])

In [67]:
arr + arr

array([[ 2,  4,  6],
       [16, 18, 20]])

In [68]:
arr * arr 

array([[  1,   4,   9],
       [ 64,  81, 100]])

In [69]:
arr - arr 

array([[0, 0, 0],
       [0, 0, 0]])

In [70]:
arr / arr

array([[1., 1., 1.],
       [1., 1., 1.]])

In [71]:
1 / arr

array([[1.        , 0.5       , 0.33333333],
       [0.125     , 0.11111111, 0.1       ]])

In [72]:
arr ** 0.5

array([[1.        , 1.41421356, 1.73205081],
       [2.82842712, 3.        , 3.16227766]])

In [73]:
arr2 = np.array([[0.1, 2, 4], [4, 8, 100]])

In [74]:
arr2

array([[  0.1,   2. ,   4. ],
       [  4. ,   8. , 100. ]])

In [75]:
arr > arr2 #Comparisons between arrays of the same size yield boolean arrays

array([[ True, False, False],
       [ True,  True, False]])

## Basic Indexing and Slicing

In [76]:
arr = np.arange(20)

In [77]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [78]:
arr[5]

5

In [79]:
arr[5:8]

array([5, 6, 7])

In [80]:
arr[5:8] = 71 #Broadcasting

In [81]:
arr

array([ 0,  1,  2,  3,  4, 71, 71, 71,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [82]:
arr_slice = arr[5:8]

In [83]:
arr_slice[1] = 80000745

In [84]:
arr

array([       0,        1,        2,        3,        4,       71,
       80000745,       71,        8,        9,       10,       11,
             12,       13,       14,       15,       16,       17,
             18,       19])

The “bare” slice [:] will assign to ll values in an array

In [85]:
arr_slice[:] = 555

In [86]:
arr

array([  0,   1,   2,   3,   4, 555, 555, 555,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19])

In [87]:
arr_copy = arr[5:8].copy() # copy() doesnt create view but copies it

In [88]:
arr_copy[:] = 111111

In [89]:
arr

array([  0,   1,   2,   3,   4, 555, 555, 555,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19])

In [90]:
%who

arr	 arr1	 arr2	 arr3	 arr4	 arr_copy	 arr_slice	 data	 data1	 
data2	 float_arr	 int_arr	 my_arr	 my_list	 np	 string_arr	 


In [91]:
arr2d = np.array([[1, 5, 9], [7, 5, 3]])

In [92]:
arr2d

array([[1, 5, 9],
       [7, 5, 3]])

In [93]:
arr = arr2d[1]

In [94]:
arr

array([7, 5, 3])

In [95]:
arr2d[0][2] #[rows][columns]

9

In [96]:
arr2d[0, 2]

9

In [97]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

In [98]:
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [99]:
arr3d[0] #arr3d[0] is a 2 × 3 array

array([[1, 2, 3],
       [4, 5, 6]])

In [100]:
arr3d[1]

array([[ 7,  8,  9],
       [10, 11, 12]])

In [101]:
old_values = arr3d[0].copy()

In [102]:
old_values

array([[1, 2, 3],
       [4, 5, 6]])

In [103]:
arr3d[0] = 42

In [104]:
arr3d

array([[[42, 42, 42],
        [42, 42, 42]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [105]:
arr3d[0] = old_values

In [106]:
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [107]:
arr3d[1, 0]

array([7, 8, 9])

In [108]:
x = arr3d[1]

In [109]:
x

array([[ 7,  8,  9],
       [10, 11, 12]])

In [110]:
x[0]

array([7, 8, 9])

In [111]:
arr = np.arange(15)

In [112]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [113]:
arr[1:5]

array([1, 2, 3, 4])

In [114]:
arr2d

array([[1, 5, 9],
       [7, 5, 3]])

In [115]:
arr2d[:2]

array([[1, 5, 9],
       [7, 5, 3]])

In [116]:
arr2d[:2, 1:]

array([[5, 9],
       [5, 3]])

In [117]:
arr2d

array([[1, 5, 9],
       [7, 5, 3]])

In [118]:
arr2d[1,:2]

array([7, 5])

In [119]:
arr2d[:,:1]

array([[1],
       [7]])

In [120]:
arr2d[:,0]

array([1, 7])

In [121]:
arr2d

array([[1, 5, 9],
       [7, 5, 3]])

In [122]:
arr2d[0,1:] = -5875

In [123]:
arr2d

array([[    1, -5875, -5875],
       [    7,     5,     3]])

## Boolean Indexing

In [124]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])

In [125]:
names

array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'], dtype='<U4')

In [126]:
data = np.random.randn(7, 4)

In [127]:
data

array([[ 2.09735654,  0.05135475, -0.33857504, -0.4437792 ],
       [ 1.78180436,  0.20377725,  0.08291648,  0.4693138 ],
       [ 0.92279167,  0.52115946,  0.16553396,  1.14968692],
       [-0.54539908, -2.02454296,  0.77456108,  1.0900093 ],
       [ 1.6561738 ,  0.9801765 , -0.44233486,  0.78859752],
       [-0.4414985 ,  2.98863482,  0.58159764, -0.7949198 ],
       [-0.4636559 ,  1.22330462,  1.38027402, -1.1836022 ]])

In [128]:
names == 'Bob'

array([ True, False, False,  True, False, False, False])

In [129]:
data[names == 'Bob']

array([[ 2.09735654,  0.05135475, -0.33857504, -0.4437792 ],
       [-0.54539908, -2.02454296,  0.77456108,  1.0900093 ]])

In [130]:
data[names == 'Bob', 2:]

array([[-0.33857504, -0.4437792 ],
       [ 0.77456108,  1.0900093 ]])

In [131]:
names != 'Bob'

array([False,  True,  True, False,  True,  True,  True])

In [132]:
data[names != 'Bob']

array([[ 1.78180436,  0.20377725,  0.08291648,  0.4693138 ],
       [ 0.92279167,  0.52115946,  0.16553396,  1.14968692],
       [ 1.6561738 ,  0.9801765 , -0.44233486,  0.78859752],
       [-0.4414985 ,  2.98863482,  0.58159764, -0.7949198 ],
       [-0.4636559 ,  1.22330462,  1.38027402, -1.1836022 ]])

In [133]:
data[~(names == 'Bob')] # ~ is used to invert a general condition

array([[ 1.78180436,  0.20377725,  0.08291648,  0.4693138 ],
       [ 0.92279167,  0.52115946,  0.16553396,  1.14968692],
       [ 1.6561738 ,  0.9801765 , -0.44233486,  0.78859752],
       [-0.4414985 ,  2.98863482,  0.58159764, -0.7949198 ],
       [-0.4636559 ,  1.22330462,  1.38027402, -1.1836022 ]])

In [134]:
cond = names == 'Joe'

In [135]:
data[~cond]

array([[ 2.09735654,  0.05135475, -0.33857504, -0.4437792 ],
       [ 0.92279167,  0.52115946,  0.16553396,  1.14968692],
       [-0.54539908, -2.02454296,  0.77456108,  1.0900093 ],
       [ 1.6561738 ,  0.9801765 , -0.44233486,  0.78859752]])

In [136]:
mask = (names == 'Bob') | (names == 'Joe')

In [137]:
data[mask]

array([[ 2.09735654,  0.05135475, -0.33857504, -0.4437792 ],
       [ 1.78180436,  0.20377725,  0.08291648,  0.4693138 ],
       [-0.54539908, -2.02454296,  0.77456108,  1.0900093 ],
       [-0.4414985 ,  2.98863482,  0.58159764, -0.7949198 ],
       [-0.4636559 ,  1.22330462,  1.38027402, -1.1836022 ]])

In [138]:
data[~mask]

array([[ 0.92279167,  0.52115946,  0.16553396,  1.14968692],
       [ 1.6561738 ,  0.9801765 , -0.44233486,  0.78859752]])

In [139]:
data

array([[ 2.09735654,  0.05135475, -0.33857504, -0.4437792 ],
       [ 1.78180436,  0.20377725,  0.08291648,  0.4693138 ],
       [ 0.92279167,  0.52115946,  0.16553396,  1.14968692],
       [-0.54539908, -2.02454296,  0.77456108,  1.0900093 ],
       [ 1.6561738 ,  0.9801765 , -0.44233486,  0.78859752],
       [-0.4414985 ,  2.98863482,  0.58159764, -0.7949198 ],
       [-0.4636559 ,  1.22330462,  1.38027402, -1.1836022 ]])

In [140]:
data[data < 0] = 0

In [141]:
data

array([[2.09735654, 0.05135475, 0.        , 0.        ],
       [1.78180436, 0.20377725, 0.08291648, 0.4693138 ],
       [0.92279167, 0.52115946, 0.16553396, 1.14968692],
       [0.        , 0.        , 0.77456108, 1.0900093 ],
       [1.6561738 , 0.9801765 , 0.        , 0.78859752],
       [0.        , 2.98863482, 0.58159764, 0.        ],
       [0.        , 1.22330462, 1.38027402, 0.        ]])

In [142]:
data[names != 'Joe'] = 7

In [143]:
data

array([[7.        , 7.        , 7.        , 7.        ],
       [1.78180436, 0.20377725, 0.08291648, 0.4693138 ],
       [7.        , 7.        , 7.        , 7.        ],
       [7.        , 7.        , 7.        , 7.        ],
       [7.        , 7.        , 7.        , 7.        ],
       [0.        , 2.98863482, 0.58159764, 0.        ],
       [0.        , 1.22330462, 1.38027402, 0.        ]])

## Fancy Indexing


In [144]:
arr = np.empty((8, 5))

In [145]:
arr

array([[1.20703320e-311, 1.20703643e-311, 2.14321575e-312,
        2.01589600e-312, 2.22809558e-312],
       [2.14321575e-312, 1.93101617e-312, 1.01855798e-312,
        6.79038653e-313, 9.33678148e-313],
       [1.16709769e-312, 6.79038653e-313, 1.97345609e-312,
        6.79038653e-313, 2.37663529e-312],
       [2.35541533e-312, 2.48273508e-312, 2.14321575e-312,
        6.79038654e-313, 6.79038654e-313],
       [2.33419537e-312, 2.44029516e-312, 2.05833592e-312,
        2.41907520e-312, 2.56761491e-312],
       [2.35541533e-312, 6.79038654e-313, 2.20687562e-312,
        6.79038654e-313, 2.05833592e-312],
       [2.14321575e-312, 2.44029516e-312, 2.05833592e-312,
        2.14321575e-312, 2.05833592e-312],
       [2.12199579e-312, 2.12199579e-312, 2.56761491e-312,
        2.14321575e-312, 1.20704470e-311]])

In [146]:
for i in range(arr.shape[0]):
    arr[i] = i

In [147]:
arr

array([[0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1.],
       [2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3.],
       [4., 4., 4., 4., 4.],
       [5., 5., 5., 5., 5.],
       [6., 6., 6., 6., 6.],
       [7., 7., 7., 7., 7.]])

In [148]:
arr[[5, 6, 2, 0]]

array([[5., 5., 5., 5., 5.],
       [6., 6., 6., 6., 6.],
       [2., 2., 2., 2., 2.],
       [0., 0., 0., 0., 0.]])

In [149]:
arr[[-2, 5, -4]]

array([[6., 6., 6., 6., 6.],
       [5., 5., 5., 5., 5.],
       [4., 4., 4., 4., 4.]])

In [150]:
arr = np.arange(24).reshape(8,3)

In [151]:
arr

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23]])

In [152]:
arr[[0, 5, 1] , [0, 2, 1]] #Elements (0, 0), (5, 2), (1, 1) are selected

array([ 0, 17,  4])

In [153]:
arr[[1, 2, 5, 3], [1, 2, 1, 0]]

array([ 4,  8, 16,  9])

In [154]:
arr[[1, 2, 5, 3], [1, 2, 1, 0]] = 999

In [155]:
arr

array([[  0,   1,   2],
       [  3, 999,   5],
       [  6,   7, 999],
       [999,  10,  11],
       [ 12,  13,  14],
       [ 15, 999,  17],
       [ 18,  19,  20],
       [ 21,  22,  23]])

In [156]:
arr = np.arange(32).reshape(8, 4)

In [157]:
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [158]:
arr[[0, 1, 2, 3], [0, 1, 2, 3]]

array([ 0,  5, 10, 15])

In [159]:
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [161]:
arr[[1, 5, 7, 2]][:, [0, 3, 1, 2]]

array([[ 4,  7,  5,  6],
       [20, 23, 21, 22],
       [28, 31, 29, 30],
       [ 8, 11,  9, 10]])

In [164]:
arr[[1, 5, 7, 2]][:, [0, 3, 1, 2]]

array([[ 4,  7,  5,  6],
       [20, 23, 21, 22],
       [28, 31, 29, 30],
       [ 8, 11,  9, 10]])

In [165]:
arr[[1, 5, 7, 2]] = arr[[1, 5, 7, 2]][:, [0, 3, 1, 2]]

In [166]:
arr

array([[ 0,  1,  2,  3],
       [ 4,  7,  5,  6],
       [ 8, 11,  9, 10],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 23, 21, 22],
       [24, 25, 26, 27],
       [28, 31, 29, 30]])

Keep in mind that fancy indexing, unlike slicing, always copies the data into a new array.

## Transposing Arrays and Swapping Axes


In [167]:
arr = np.arange(15).reshape(3, 5)

In [168]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [169]:
arr.T # .T -> Transpose

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [171]:
arr.transpose() # .transpose() -> Transpose

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [172]:
arr = np.random.randn(4, 5)

In [173]:
arr

array([[ 0.09052492, -1.98724714,  1.42170285, -1.232318  ,  0.13493215],
       [ 0.26245791, -0.88084365,  0.48510298, -0.75453265, -2.30590671],
       [-1.27679859, -1.0830747 ,  0.59220034, -0.11416417,  0.55171161],
       [-1.18346487,  0.5920454 ,  0.11967745, -0.34579797, -0.51490196]])

In [174]:
np.dot(arr, arr.T)

array([[ 7.5153993 ,  3.08256851,  3.09381811, -0.75687158],
       [ 3.08256851,  6.96661986, -0.27986319,  0.67417847],
       [ 3.09381811, -0.27986319,  3.47138584,  0.69609027],
       [-0.75687158,  0.67417847,  0.69609027,  2.1501298 ]])

In [178]:
arr3d = np.arange(18).reshape(3, 2, 3)

In [179]:
arr3d

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]],

       [[12, 13, 14],
        [15, 16, 17]]])

In [180]:
arr3d.T

array([[[ 0,  6, 12],
        [ 3,  9, 15]],

       [[ 1,  7, 13],
        [ 4, 10, 16]],

       [[ 2,  8, 14],
        [ 5, 11, 17]]])

In [183]:
arr3d.transpose((1, 0, 2)) # (axis0, axis1, axis2)

array([[[ 0,  1,  2],
        [ 6,  7,  8],
        [12, 13, 14]],

       [[ 3,  4,  5],
        [ 9, 10, 11],
        [15, 16, 17]]])

In [185]:
arr3d

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]],

       [[12, 13, 14],
        [15, 16, 17]]])

In [186]:
arr3d.shape

(3, 2, 3)

In [187]:
arr3d.swapaxes(2, 0)

array([[[ 0,  6, 12],
        [ 3,  9, 15]],

       [[ 1,  7, 13],
        [ 4, 10, 16]],

       [[ 2,  8, 14],
        [ 5, 11, 17]]])

# 4.2 Universal Functions: Fast Element-Wise Array Functions

A universal function, or ufunc, is a function that performs element-wise operations on data in ndarrays. You can think of them as fast vectorized wrappers for simple functions that take one or more scalar values and produce one or more scalar results.

In [188]:
arr = np.arange(10)

In [189]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [190]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [192]:
np.square(arr)

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)

In [193]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

These are referred to as unary ufuncs as they take single object to compute on

In [195]:
x = np.random.randn(8)

In [196]:
x

array([ 0.67891231, -0.86125114, -1.44837794, -0.0963337 ,  1.37250955,
       -0.36577079,  0.04166798,  1.5470388 ])

In [197]:
y = np.random.randn(8)

In [198]:
y

array([ 0.08615523, -0.1394466 ,  0.36441819,  0.38132022, -0.22188898,
        1.33753425,  0.50386169,  0.2445474 ])

In [199]:
np.maximum(x, y) #Element-wise

array([ 0.67891231, -0.1394466 ,  0.36441819,  0.38132022,  1.37250955,
        1.33753425,  0.50386169,  1.5470388 ])

In [202]:
arr = np.random.randn(8) * 5

In [203]:
arr

array([-1.05344917,  0.16249576, -0.45381053, -0.36330004, -1.42722857,
       -6.50993095, -3.02463219, -2.64110738])

In [205]:
remainder, whole_part = np.modf(arr) # .modf() returns 2 objects one is remainder and other one is its whole part

In [206]:
remainder

array([-0.05344917,  0.16249576, -0.45381053, -0.36330004, -0.42722857,
       -0.50993095, -0.02463219, -0.64110738])

In [211]:
whole_part

array([-1.,  0., -0., -0., -1., -6., -3., -2.])

In [216]:
np.abs(whole_part) #Compute the absolute value element-wise for integer, „oating-point, or complex values

array([1., 0., 0., 0., 1., 6., 3., 2.])

In [217]:
arr

array([-1.05344917,  0.16249576, -0.45381053, -0.36330004, -1.42722857,
       -6.50993095, -3.02463219, -2.64110738])

In [218]:
np.sqrt(arr) #Compute the square root of each element (equivalent to arr ** 0.5)

C:\Users\ABC\anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in sqrt
  """Entry point for launching an IPython kernel.


array([       nan, 0.40310762,        nan,        nan,        nan,
              nan,        nan,        nan])

In [219]:
np.sqrt(arr, arr)

C:\Users\ABC\anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in sqrt
  """Entry point for launching an IPython kernel.


array([       nan, 0.40310762,        nan,        nan,        nan,
              nan,        nan,        nan])

In [222]:
arr = np.arange(15)

In [223]:
np.log(arr) #Natural logarithm (base e)

C:\Users\ABC\anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458,
       2.30258509, 2.39789527, 2.48490665, 2.56494936, 2.63905733])

In [225]:
np.exp(arr) #Compute the exponent exp of each element

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04, 5.98741417e+04,
       1.62754791e+05, 4.42413392e+05, 1.20260428e+06])

In [230]:
arr[4] = -1

In [231]:
arr

array([ 0,  1,  2,  3, -1,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [232]:
np.sign(arr) #Compute the sign of each element: 1 (positive), 0 (zero), or –1 (negative)

array([ 0,  1,  1,  1, -1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1])

In [233]:
arr

array([ 0,  1,  2,  3, -1,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [239]:
arr = np.array([2, 5.68, 2.0003, 7, -85.36, 985.99, 100.54])

In [240]:
arr

array([  2.    ,   5.68  ,   2.0003,   7.    , -85.36  , 985.99  ,
       100.54  ])

In [241]:
np.ceil(arr) #Compute the ceiling of each element (i.e., the smallest integer greater than or equal to that number)

array([  2.,   6.,   3.,   7., -85., 986., 101.])

In [243]:
np.floor(arr) #Compute the foor of each element (i.e., the largest integer less than or equal to each element)

array([  2.,   5.,   2.,   7., -86., 985., 100.])

In [245]:
np.rint(arr) #Round elements to the nearest integer, preserving the dtype

array([  2.,   6.,   2.,   7., -85., 986., 101.])

In [247]:
arr = np.array([5, 2.30, 87, np.nan])

In [248]:
arr

array([ 5. ,  2.3, 87. ,  nan])

In [250]:
np.isnan(arr)

array([False, False, False,  True])

See Tables 4-3 (Unary ufuncs) and 4-4 (Binary ufuncs) for a listing of available ufuncs.